export const queryKeys = {
  register: "register",
  login: "login",
  logout: "logout",
  userInfo: "user-info",
  projectList: "project-list",
  projectInfo: "project-info",
  addProject: "add-project",
  deleteProject: "delete-project",
  editProject: "edit-project",
  viewProjectTasks: "view-project-tasks",
  addTask: "add-task",
  updateTask: "update-task",
  deleteTask: "delete-task",
  viewProjectMember: "view-project-member",
  removeMember: "remove-project-member",
  addMember: "add-project-member",
};
